### ISSUE TITLE
Add check to see if bootstrap is already loaded.

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3#314]
Currently an isjQueryLoaded function is provided in the entry point but we do not provide the same functionality for bootstrap.  If bootstrap is added via the script tag it gets added twice.

**Comment by amitmun** [comment]
+1
We're using the GWT app together with regular pages (mostly used for sign-up, sign-in, forgot password etc.) and we would like to use the same fragment to load Bootstrap for all pages. Currently we have a different fragment specially for the GWT app page because we don't want to load the JS twice.
