### ISSUE TITLE
AnchorListItem not working well with UiHandler annotation

### ISSUE THREAD

**Issue by steeveb972** [gwtbootstrap3/gwtbootstrap3#353]
Hi,

I use AnchorListItem in my project, and I had a problem to get clikHandler working. I use @UiHandler annotation to add a click listener to my instance of AnchorListItem among other widgets.
When I receive an event I use event.getSource() to know which widget has triggered the event.

It doesn't work with AnchorListItem, because the trigger is not the AnchorListItem, but the underlying anchor Widget (I saw this in debug, confirmed by the source code in AbstractAnchorListItem).

I suggest either to match the real source widget for the event (which is cleaner), or to let read access to the underlying widget to match the source (not my preferred way because I suppose you want to let Anchor hidden).

As a workaround, I call getParent() on the source widget of the event, but I don't know if this will be clear for anyone who uses this project.

Regards,

Steeve Beroard

**Comment by jgodi** [comment]
Good point. Can you submit a PR for this improvement?

**Comment by sjardine** [comment]
@steeveb972 - Would you be able to submit a PR for this improvement?

**Comment by steeveb972** [comment]
Hi all,

Sorry for the late reply, honestly I can't see any "clean" workaround without some refactoring, but as soon as I have got one, I will submit a PR for that!

**Comment by crevete** [comment]
@v00d00 Thanks for your PR. But the original implementation seems correct.

The ```AnchorListItem``` is just a wrapper of ```Anchor``` widget, and it delegates all to the inner anchor. I don't really understand the bug description. If the bug for the author was : ```event.getSource()``` returns ```Anchor``` rather than ```AnchorListItem```, it is normal for me.

**Comment by v00d00** [comment]
Hi,

Usually 

> Widgets declare themselves as the source of an event when they invoke a handler method, allowing a single handler to distinguish between multiple event publishers with an event object’s getSource() method.

People using UiBinder have no idea about the inner `Anchor` element (Only the `AnchorListItem`, and we shouldnt have to know about the implementation), so we cannot do as in the the UIBinder docs[1] and check against our `@UiField`s.

1. http://www.gwtproject.org/doc/latest/DevGuideUiHandlers.html

**Comment by crevete** [comment]
Not exactly. What you said is right only if the widget declares itself as an event source (like ```Anchor``` widget). In this case, ```event.getSource()``` returns the widget itself. However, when using event delegation (like ```AnchorListItem```), ```event.getSource()``` could never retrieve the wrapper widget and you have to do some DOM manipulation to determine whether or not the wrapper widget is "event source".

Please check the response of Thomas Broyer at bottom of [this thread](http://stackoverflow.com/questions/9825572/how-do-i-get-from-the-event-object-the-object-on-which-there-was-this-event)

**Comment by v00d00** [comment]
`AnchorListItem` is a widget and it implements `HasClickHandlers`, how is that not an event source? I think it reasonable to assume that the widget that you bind your handler to is the source of the event.

We are not trying to do event delegation over any _elements_, we are trying to as Thomas Broyer says at the top of the post in the link you provided, have a single handler bound to multiple _widgets_ and use getSource() to differentiate.

By returning an internal implementation detail (the `Anchor`) you are essentially this forcing users to look at the implementation of the widget, which just breaks the OO principle of encapsulation entirely.

**Comment by crevete** [comment]
Well I don't say you are using event delegation, I mean the author of this widget did it on ```AnchorListItem```. I perfectly understant what you mean. Let's take the example below :

```
<div id="firstDiv">
  <div id="secondDiv">
    ...
      <div id="lastDiv">
         <a>Link</a>
      </div>
  </div>
</div>
```

**Currently :**
The click event is fired at ```<a>``` (event source or event target),  the ```firstDiv``` (wrapper widget) does not fire click event.

**Your suggestion :** 
The click event is not fired at ```<a>``` but ```firstDiv``` which becomes event source. The behaviour is completely changed!

That's why I said for widgets using event delegation (like ```AnchorListItem```), event.getSrouce is not supposed to get the widget itself.

Beside, if every widget has a its own click handler (I mean every click handler is different), why you absolutely want to implement a "universal" click handler and differentiate them with ```getSource()``` ? What's the gain ? Just some handler objects for each widget ? With current web browsers performances, this costs nothing...

**Comment by v00d00** [comment]
We could have a click handler per widget absolutely, but that is a bad workaround.

A widgets purpose is to abstract its internal implementation, the way the code is now is breaking a well documented pattern and gives no advantages.

There is no "delegation" here, you are just binding the handler to the wrong thing.

There will be no change in behaviour, please try the patch and see it for yourself. The end result is the same (as the click from the `Anchor` bubbles to the ListItem).

**Comment by crevete** [comment]
I've tried your patch... You don't understand what I mean. Of course the behaviour will change. In your case with our ```AnchorListItem``` widget, it looks like that nothing changes. But in fact, as I said, the click event will be fired on the wrapping div rather than the inner anchor. Imagine, if you put some CSS (like a big padding) on the wrapping div, you can just click every where on the div to get click event fired. But if we keep the original implemetation, you can only click on the anchor to get click event fired. That is totolly different.

**Comment by v00d00** [comment]
Surely it is the correct behaviour if you add a `ClickHandler` to an `AnchorListItem` widget, that you can click anywhere on the widget and get an event fired?

**Comment by crevete** [comment]
Your point of view on ```AnchorListItem``` may be right, but according to the author's code, the click event should be fired ONLY on the inner anchor.

When you implement a searchBox for example, something like this :
```<div><input type="text"/></div>```
A widget (div) containing an inner input text that fires keyboard event. This widget should implement
```HasAllKeyHandlers``` or not? It's the same issue here. According to your logic, the div should capture all key events, rather than inner input. Is this really what we want ?

**Comment by steeveb972** [comment]
Hi all,

One idea is maybe the AnchorListItem could wrap the ClickHandler that is passed to the Anchor as a delegate, then in case of an event, it substitutes the Anchor by AnchorListItem as a Source. What do you think?

**Comment by crevete** [comment]
@steeveb972 Could you please give some sample code?

**Comment by v00d00** [comment]
> When you implement a searchBox for example, something like this :
<div><input type="text"/></div>
A widget (div) containing an inner input text that fires keyboard event. This widget should implement
HasAllKeyHandlers or not? It's the same issue here. According to your logic, the div should capture all key events, rather than inner input. Is this really what we want ?

Absolutely it should implement `HasAllKeyHandlers` and the source should be widget object itself, no elements.

**Comment by crevete** [comment]
@v00d00 I'm sorry, I confirm that the behavior of ```AnchorListItem``` WILL be changed if we follow your suggestion. Please try with our demo page http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#typography on section _Lists_.

In fact, now only **the anchor "item"** is clickable if we bind a click handler on ```AnchorListItem```. However, if we change event source like your suggestion, the **whole line** (including all blank spaces at the right side of the anchor "item") will be clickable. And this is absolutely NOT what we want... I hope you are agree with me at this point at least...

So the author's implementation is correct. If you insist, maybe we should remove ```implement HasClickHandlers``` on ```AnchorListItem```, and add a method like ```addAnchorClickHandler(handler)```. But as you said in the previous post, the widget should implement the ```HasClickHandlers``` interface. Otherwise it will be really strange...

One more time, please note that ```event.getSource``` returns the real event target that fires the event ; and it does not always return the current widget itself! All simple widgets (with just one HTML tag, like anchor, etc.) can declare themselves as event source, but others (with more complex DOM structure) _NOT ALWAYS_, since it depends on implementation.

The correct way for me to get your code work is, as I said :
```
@UiHandler("myWidget")
void handleClick(ClickEvent event) {
    // NOT DO THIS
    // if (event.getSource() == myWidget) doSomeThing();
    // But DO THIS and it always works :
    if (myWidget.getElement().isOrHasChild(Element.as(event.getNativeEvent().getEventTarget())))
        doSomeThing();
```

**Comment by steeveb972** [comment]
I had a look on GWT base code on a similar Widget called SuggestBox that implements the behavior I described, so I suggest to modify **AbstractAnchorListItem** and all other composite like this one as following:
- first in the constructor
`protected AbstractAnchorListItem() {
        anchor = new Anchor();
        anchor.addClickHandler(new ClickHandler() {
			
			@Override
			public void onClick(ClickEvent event) {
				delegateEvent(AbstractAnchorListItem.this, event);
			}
		});
        add(anchor, (Element) getElement());
    }`

and then the addClickHandler method becomes:
`public HandlerRegistration addClickHandler(final ClickHandler handler) {
        return addDomHandler(handler, ClickEvent.getType());
    }` 

and that's it :) the event is properly attached to the anchor and delegated to the widget.
I tested that code and it works properly.

**Comment by steeveb972** [comment]
A little fix, I think it's better to use addHandler instead of addDomHandler to fulfill all requirements (like in SuggestBox)

**Comment by crevete** [comment]
@steeveb972 I've checked it, this looks like the right solution for this kind of situation. I'll make a PR soon. Thanks again!
