### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3#413]
Discussion on how to implement upcoming bootstrap 4.  Please give suggestion's comments on the implementation of gwt and bootstrap 4.

**Comment by crevete** [comment]
http://v4-alpha.getbootstrap.com/migration/

I think we should create a new project named "gwtbootstrap4" but based on the current project.

**Comment by remarkNS** [comment]
Just few thoughts about the future version(s):

- As UIBinder will probably not be supported in GWT 3.0:
Use plain html/css instead of UIBinder and wrap existing tags from html template to Element wrapper components. This is something that RedHat Errai is doing (with widgets in this moment, they are working on element version as well) or you can take a look how this is working in CodeLess Meta Platform here: https://www.youtube.com/watch?v=ROZ5Oa6DoUg (also with widgets in this moment, using slightly modified GWTBootstrap3 - basicly the only change is to add constructor with Element in every component that needs to be wrapped instead of creating it internally). Complete layout with Row, Column, Panels, ... all of this can be written in simple html including all "form" components. In UIBinder you do the same as you are mimicking html. I don't think this is necessary at all. With html template binding one can copy existing html, there is no need to write it manually again in UIBinder. From the link above you can see how this can work dynamically without even leaving the browser (replacing one login screen with another from bootsnipp with simple copy/paste). Does not have to be that way, it can be pure client side as well. Other example of this technique: https://www.youtube.com/watch?v=ybb8I9xJGOA&index=11&list=PL40n9mhU-gRD1_fb7-uWEhC8lUBUQayyi and small demo: http://metaplatform-codelessolutions.rhcloud.com/MetaPlatform/index.html?name=user3&password=user3

- As it's hard to keep new versions in sync with limited sources:
Use/Build some kind of tool to create java wrapper classes from JS components automaticaly like this tool https://github.com/vaadin/gwt-api-generator is creating gwt-polymer library from polymer JS library (there is two versions: widget and element in this moment).

- As some other things will probably also be gone in GWT 3.0:
Replace GWT Grid/CellTable with something modern, feature rich and responsive like Vaadin Grid or something else that can be used as webcomponent / implemented with new JsInterop instead of JSNI. GwtMaterial team is building their own Grid and Tree that will be GWT 2.8/3.0 compatible. Maybe that can also be used with GwtBootstrap4+ as well. 

It's reasonable to do what @crevete is suggesting, but I believe that eventually things should move over time in the direction I mentioned, at least that's what I think. Just giving you my 2 cents...

**Comment by payammeyer** [comment]
Bootstrap 4 finally released:

https://mdbootstrap.com/bootstrap-4-stable/?_utm_source=1-2-2

**Comment by mxlse** [comment]
And here is the final migration documentation: https://getbootstrap.com/docs/4.0/migration/

**Comment by sjardine** [comment]
I currently don't have any plans to work on gwtbootstrap4.
