### ISSUE TITLE
Release 0.9.2

### ISSUE THREAD

**Issue by crevete** [gwtbootstrap3/gwtbootstrap3#439]
I think it is time to get things move from now. How about to make a 0.9.2 release. Since 1.0 is still far for me. What's your opinion @sjardine?

**Comment by sjardine** [comment]
I think there have been enough changes from 0.9.1 to justify a 0.9.2 release.  I have been trying to resolve the main lib issues but I agree that we aren't ready for a 1.0.0.

I will start working on a release.  Are there any issues that need to be complete before the 0.9.2 release?

**Comment by crevete** [comment]
Not really. Personally I plan to rewrite the bootstrap select wrapper, but if we continue to make some maintenance releases (0.9.x), this could be done later. Besides, I'm not pretty sure I will have enough time before January 2016.

**Comment by sjardine** [comment]
I would still like your opinion on how we can rewrite the validation stuff to be able to allow it with some of these form extras.  I realize the that the implementation is sub optimal in some areas.  I would be happy to make changes you felt were necessary to make the implementation better.

I will go forward with the release.  I don't think the api has changed much so there may not need to be an upgrade doc.  I will review the changes since 0.9.1 and create the doc if needed.  I would suggest a code freeze until I can get the release complete.  Should be sometime this week.

**Comment by crevete** [comment]
Great if you can review the changes since 0.9.1. I agree with the code freeze from now. And we should create a new milestone and put some closed issue into this release.

For validation stuff, I would suggest that we provide a kind of "contract", as you did for bootstrap basic widgets, and a default implementation as your suggestion. By this way, people would be able to implement their own validation stuff if the default one is not convenient for them.

**Comment by sjardine** [comment]
@crevete I have created releases for gwtbootstrap3 and gwtbootstrap3-extras.  Would you mind looking at the release notes to see if I missed anything important?  The 0.9.2 release has been made to maven central for gwtbootstrap3 but not gwtbootstrap3-extras.  Should be synced later today.

I am working on updating the documentation and the demo.

**Comment by crevete** [comment]
Thanks @sjardine, I've just fixed some versions of extra widgets in the release notes.

**Comment by sjardine** [comment]
The release is pretty much complete.  Once maven central sync's gwtbootstrap3-extras I will make an announcement on the gwtboostrap3 google group.

**Comment by crevete** [comment]
I think it's done on the maven central :-)
