### ISSUE TITLE
Support for glyphicons

### ISSUE THREAD

**Issue by rlf** [gwtbootstrap3/gwtbootstrap3#469]
Currently the glyphicons are available, but using them on buttons are a pain - since they are not cooked into the IconType or Styles.

I know it's on the TODO list - but please prioritize it.

**Comment by crevete** [comment]
I'm not sure this is on the TODO list and should be prioritized...
Glyphicons are becoming obsolete and will be completly dropped soon:
http://v4-alpha.getbootstrap.com/migration/#components

**Comment by rlf** [comment]
Having FA hardcoded into GWTBootstrap is the problem.
As the above link mentions, there are a number of ways to add icons.
A possible solution would be, to allow the IconType to be customized (i.e. take a string, instead of an enum).
Either that, or support the enums of different "icon sets", either all, or included as a module (as the TODO.md states).

**Comment by crevete** [comment]
I think the best way is to make a module for each icon set. But it's not simple to extract an common interface; because each icon set supports different "features" (position, flip, rotate, spin, pulse, bordered, etc.). ==> this is something we could do, but not implement a module for glyphicon

Another approach is (as you said) to add an another enum of the new icon set. This is the simplest way and you can just extend existing widgets (Button, etc.) to set the icon you want.

To allow the iconType to be customized is not a great solution for an API like this, but you could anyway do this manually (to add a span, with a class you want, etc.)

**Comment by rlf** [comment]
I know.
But adding spans becomes increasingly cumbersome, if you (as we do), rely on a lot of GWTBootstrap3 components. It basically means you need to wrap most of the "icon-enabled" components.

I did find a (hacky) workaround though, that I might share - but it's not suitable for the light of day :)
