### ISSUE TITLE
Can't add css style to Slider?

### ISSUE THREAD

**Issue by flyinghang** [gwtbootstrap3/gwtbootstrap3#472]
I am trying to change the width of a Slider to "100%" like this:

`<b3:Slider min="0" value="30" max="100" addStyleNames="my-slider"/>`

and the css is like:

`.my-slider {
    width: 100% !important;
    margin-left: 24px;
}
`

gwtbootstrap3 0.9.3 with GWT 2.7

the css is not working, it seems it applies to the generated Input element (invisible) not the Div with class "slider". Not sure if this is an already reported issue but it seems that I can't customize the widget in Ui Binder. 

Any comments to this issue?

**Comment by sjardine** [comment]
This issue actually belongs to the gwtbootstrap3-extras project.  Please re-file it there.

I have verified the my-slider class is getting applied to the hidden input element.  It would be ideal if the css applied to the top level div rather than the input element but I am not sure there is any good way to do this since those divs get created by the slider js code.

**Comment by crevete** [comment]
cf. gwtbootstrap3/gwtbootstrap3-extras#297

**Comment by flyinghang** [comment]
Thank you @sjardine
